### ISSUE TITLE
6.5.53 tag fails to run with ld.so errors

### ISSUE THREAD

**Issue by zemsten** [linuxserver/docker-unifi-controller#103]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

1. Pull new image tag -- 6.5.53
2. Recreate container, keeping the same persistent volumes
3. Container starts, database migration occurs, Unifi is served

## Current Behavior

Container image pulls correctly and is the amd64 image. Starting the container appears to work properly, getting through the initial supervisor steps of settings permissions, etc. Upon commencement of the Unifi app though, the log is continuously flooded with
```
"elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed"
```
 errors and the web UI is not accessible.

## Steps to Reproduce

1. Start with a working previous image.
2. Recreate container with the new tag on 6.5.53
3. Observe docker logs for the unifi-controller container
4.

## Environment
**OS:** Debian 11
**CPU architecture:** x86_64
**How docker service was installed:** from official docker repo

## Command used to create docker container (run/create/compose/screenshot)

docker-compose v2
excerpt from the docker-compose.yml file shown below
```
##############################################################                             
#UNIFI CONTROLLER                                                                          
##############################################################                             
  unifi-controller:                                                                                                                                                                    
    image: ghcr.io/linuxserver/unifi-controller                                     
    container_name: unifi-controller                                                       
    environment:                                                                           
      - PUID=1337                                                                          
      - PGID=1337
      - MEM_LIMIT=1024M #optional
    volumes:
      - /docker/unifi/unifi-config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8081:8080
        #      - 8443:8443
        #      - 1900:1900/udp #optional
        #      - 8843:8843 #optional
        #      - 8880:8880 #optional
        #      - 6789:6789 #optional
        #      - 5514:5514 #optional
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi-controller.rule=Host(`unifi.mydomain.tld`)"
      - "traefik.http.services.unifi-controller.loadbalancer.server.port=8443"
      - "traefik.http.routers.unifi-controller.entrypoints=websecure"
      - "traefik.http.services.unifi-controller.loadbalancer.server.scheme=https"
      - "traefik.http.routers.unifi-controller.middlewares=rate-limit@file,secure-headers@file"
    security_opt:
      - no-new-privileges:true
```

Additionally, upon attempting to downgrade, putting the 6.4.54 tag in the compose file, it starts properly without any errors shown in the docker logs, but appears to be stuck in a starting up/database migration step.

## Docker logs

I have already reverted to the previous version which wiped out my log files. If this database migration step never finishes, I'll push it back to the current tag and recreate the issue. The logs included constant messages with the 
```
"elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed"
```
 errors though.

EDIT: Here are the logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1337
User gid:    1337
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
[services.d] done.
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 540: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
```
