### ISSUE TITLE
Symlink formed in data directory (data -> /config/data)

### ISSUE THREAD

**Issue by eggbean** [linuxserver/docker-unifi-controller#116]
## Environment
**OS:** Debian 11
**CPU architecture:** arm64
**How docker service was installed:**
Ansible

## Command used to create docker container (run/create/compose/screenshot)
```
  - name: Deploy unifi-controller Docker container
    docker_container:
      image: linuxserver/unifi-controller
      name: unifi
      pull: true
      state: started
      restart_policy: unless-stopped
      detach: true
      interactive: false
      tty: false
      auto_remove: false
      container_default_behavior: no_defaults
      log_driver: none
      volumes:
        - /usr/lib/unifi/data:/usr/lib/unifi/data
      ports:
        - "3478:3478/udp"
        - "10001:10001/udp"
        - "8080:8080"
        - "8443:8443"
```

I have `/usr/lib/unifi/data` mapped to `/usr/lib/unifi/data` on the host machine, but I get this weird dead symlink (`data -> /config/data`) appear in  the directory. How do I stop this from happening? There was no such symlink when using the previous unifi docker container from somewhere else.

```
jason@amunet:/usr/lib/unifi/data$ ls -l
total 36
drwxr-xr-x 3 911 911  4096 Dec 21 13:26 backup
lrwxrwxrwx 1 911 911    12 Dec 21 13:34 data -> /config/data
drwxr-xr-x 4 911 911 20480 Dec 21 13:30 db
-rw-r--r-- 1 911 911  2250 Dec 21 13:26 keystore
-rw-r--r-- 1 911 911  1322 Dec 21 13:29 system.properties
-rw-r--r-- 1 911 911  1322 Dec 21 13:29 system.properties.bk
```
