### ISSUE TITLE
config.gateway.json ignored

### ISSUE THREAD

**Issue by Syntax3rror404** [linuxserver/docker-unifi-controller#120]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Place config.gateway.json file inside the container at `/var/lib/unifi/sites/default/config.gateway.json` to add static host mappings

## Current Behavior
config.gateway.json was placed at `/var/lib/unifi/sites/default/config.gateway.json` and will be ignored

## Steps to Reproduce

1. Place config.gateway.json file inside the container at `/var/lib/unifi/sites/default/config.gateway.json` to add static host mappings
2. Make sure you are using the right site name in my case "default"
3. Force a provision inside the web ui

## Environment
**OS:** Fedora 35
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.7"

services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - ../../volumes/unifi_controller/config:/config
      - ../../volumes/unifi_controller/config.gateway.json:/var/lib/unifi/sites/default/config.gateway.json
    ports:
      - mode: host
        protocol: udp
        published: 3478
        target: 3478
      - mode: host
        protocol: udp
        published: 10001
        target: 10001
      - mode: host
        protocol: tcp
        published: 8080
        target: 8080
      - mode: host
        protocol: tcp
        published: 8081
        target: 8081
      - mode: host
        protocol: tcp
        published: 8443
        target: 8443
      - mode: host
        protocol: tcp
        published: 8843
        target: 8843
      - mode: host
        protocol: tcp
        published: 8880
        target: 8880
      - mode: host
        protocol: tcp
        published: 6789
        target: 6789
    restart: unless-stopped
```

## Used config.gateway.json
```
{
   "system":{
      "static-host-mapping":{
         "host-name":{
            "argo.ingress.labza":{
               "alias":[
                  "argo.ingress.labza"
               ],
               "inet":[
                  "192.168.33.82"
               ]
            },
            "awx.ingress.labza":{
               "alias":[
                  "awx.ingress.labza"
               ],
               "inet":[
                  "192.168.33.82"
               ]
            },
            "tekton.ingress.labza":{
               "alias":[
                  "tekton.ingress.labza"
               ],
               "inet":[
                  "192.168.33.82"
               ]
            },
            "vault.ingress.labza":{
               "alias":[
                  "vault.ingress.labza"
               ],
               "inet":[
                  "192.168.33.82"
               ]
            }
         }
      }
   }
}
```

## Docker logs

```
[root@dockersrv2 ~]# docker logs unifi-controller
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing... 
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 8893 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (6.5.55-16678-1) ...
Setting up unifi (6.5.55-16678-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
[cont-init.d] 15-install: exited 0.
[cont-init.d] 19-deprecate: executing... 
[cont-init.d] 19-deprecate: exited 0.
[cont-init.d] 20-config: executing... 
*** Setting Java memory limit to 1024M ***
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
