### ISSUE TITLE
HTTP Status 404 – Not Found on web ui

### ISSUE THREAD

**Issue by daballiemo** [linuxserver/docker-unifi-controller#123]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
New install of docker unifi container and expecting a page to setup the new unifi manager or upload a backup

## Current Behavior
after installation when browsing to the main paige the webpage shows "HTTP Status 404 – Not Found"

## Steps to Reproduce
Start new container with docker-compose:

```
version: "3.8"

services:  
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    container_name: system_unifi_test
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 9080:8080
      - 9081:8081
      - 9443:8443
      - 9843:8843
      - 9880:8880
      - 6789:6789
    volumes:
      - /volume1/homelab/system/unifi-test/data:/config
    environment:
      - PUID=1042 # 1042 is docker user on DS918+
      - PGID=100
      - MEM_LIMIT=1024M
      - TZ=Europe/Amsterdam           
    restart: unless-stopped
    network_mode: "bridge"  
```

after the container is up, browse to "https://dockerserver:9443" and being greeted by 404 error.

after performing the following action, the correct page is shown.

docker exec -ti unifi bash
chown unifi.unifi -R /usr/lib/unifi
exit
docker restart unifi

## Environment
synology setup is DS918+/DSM 7.0-41890; docker installed via the official app store.

## Command used to create docker container (run/create/compose/screenshot)
see above

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1042
User gid:    100
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing... 
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 8893 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (6.5.55-16678-1) ...
Setting up unifi (6.5.55-16678-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
[cont-init.d] 15-install: exited 0.
[cont-init.d] 19-deprecate: executing... 
[cont-init.d] 19-deprecate: exited 0.
[cont-init.d] 20-config: executing... 
*** Setting Java memory limit to 1024M ***
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /config/data/keystore -destkeystore /config/data/keystore -deststoretype pkcs12".
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
