### ISSUE TITLE
MongoDB Exception in thread "RefreshSsoTokens"

### ISSUE THREAD

**Issue by Idan37S** [linuxserver/docker-unifi-controller#135]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Unifi Controller should run without issues

## Current Behavior

I'm getting a MongoDB exception after running the Unifi Controller for like a day or two, it keeps happening all the time. 
Once it happens Unifi Controller isn't working properly and isn't responding.
Only a restart to the container solves it temporarily till it happens again.
I'm using the latest version of the container, but it's happening to me for a few months now (like 4 months),
Just hadn't time to handle and try to solve it till now.

 
## Steps to Reproduce

I'm using Unraid v6.9.2 to host the Unifi Controller container,
And the exception just happens after a while )day or two) without doing anything.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Unraid v6.9.2
Intel i9 10850K 

## Command used to create docker container (run/create/compose/screenshot)

Unraid Community Store

## Docker logs

The exception from the logs:

Exception in thread "RefreshSsoTokens" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27117, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:377)
at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
at com.mongodb.operation.FindOperation.execute(FindOperation.java:510)
at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
at com.mongodb.Mongo.execute(Mongo.java:836)
at com.mongodb.Mongo$2.execute(Mongo.java:823)
at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
at com.ubnt.service.system.n.Ò00000(Unknown Source)
at com.ubnt.service.sso.ooOO.new(Unknown Source)
at com.ubnt.service.sso.ooOO.o00000(Unknown Source)
at com.ubnt.service.sso.ooOO$_o.run(Unknown Source)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)

**Comment by colemorgan** [comment]
Bump

**Comment by j0nnymoe** [comment]
Im not sure this is something for us to fix? We don't actually do anything with the mongodb config other than what unifi does itself during setup.

**Comment by colemorgan** [comment]
I'm not 100% sure how mongodb is getting into this state, but it takes the UniFi controller down every 1-3 days. I've tried fresh installs and this happens every time. So I assume there is something to fix, but I'm not sure if this is on the UniFi side, or mongo..

**Comment by j0nnymoe** [comment]
It's not a definite it takes down unifi every 1-3 days, my instance has been only for a number of months. I suspect there is something specific to your setup causing this otherwise I'd expect a lot more reports of this issue.

**Comment by j0nnymoe** [comment]
If someone could provide some compose etc about how they have unifi deployed, that would be good but this is likely (as we've seen many times before) an issue with unifi/mongodb than an issue with our container.

**Comment by colemorgan** [comment]
> If someone could provide some compose etc about how they have unifi deployed, that would be good but this is likely (as we've seen many times before) an issue with unifi/mongodb than an issue with our container.

Here is my compose
```
---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
       - /thedock/unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
```
