### ISSUE TITLE
default datetime/timezone is wrong in docker container

### ISSUE THREAD

**Issue by fermulator** [linuxserver/docker-unifi-controller#137]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Current Behavior
At first, I was getting the following error after running and starting setup, attempting to login to unifi account via SSO:
> "There was a problem logging into your account, please try again later."

After contacting Unifi support, they suggested actually an idea that this _could_ happen if the date/time of the system is wrong.

Sure enough ... I checked:
```
docker:~$ date
Fri Apr 15 14:30:40 EDT 2022
```
^ the host

vs
```
docker:~$ docker exec -it unifi-controller date
Fri 15 Apr 2022 06:30:40 PM UTC
```

compare to a different container (same host)
```
Fri Apr 15 14:30:40 EDT 2022
```

quick way to compare:
```
r$ date;  docker exec -it unifi-controller date; docker exec -it pihole date
Fri Apr 15 14:41:51 EDT 2022
Fri 15 Apr 2022 06:41:51 PM UTC
Fri Apr 15 14:41:51 EDT 2022
```

Yikes.

Well the container IS in the correct timezone (inherited from host presumably)
```
# cat /etc/timezone
Etc/UTC
```

NTP isn't installed. Nor can I set the date manually
```
# date --set="Fri Apr 15 14:38:00 EDT 2022"
date: cannot set date: Operation not permitted
```

## Steps to Reproduce

1. Follow setup instructions on main page.
2. Attempt to login
3. Try to fix the datetime.

## Environment
x86/64, 
```
$ docker --version
Docker version 20.10.12, build e91ed57

$ docker ps | grep unifi
248b00a02038   lscr.io/linuxserver/unifi-controller   "/init"      3 days ago     Up 3 days             0.0.0.0:3478->3478/udp, :::3478->3478/udp, 0.0.0.0:6789->6789/tcp, :::6789->6789/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 0.0.0.0:8843->8843/tcp, :::8843->8843/tcp, 0.0.0.0:5514->5514/udp, :::5514->5514/udp, 0.0.0.0:10001->10001/udp, :::10001->10001/udp, 0.0.0.0:8880->8880/tcp, :::8880->8880/tcp   unifi-controller

```

## Command used to create docker container (run/create/compose/screenshot)
```
r$ cat docker-compose.yml
---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1002
      - PGID=999
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /mnt/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
        #- 1900:1900/udp #optional   <<< requires root (disable for now)
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

# then:
IMAGE="unifi-controller"
docker-compose pull "${IMAGE}"
docker-compose rm -fsv
docker-compose up -d "${IMAGE}"
docker image prune -f

```

## Docker logs

```
r$ docker logs unifi-controller
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    999
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing...
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 8893 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.0.25-17292-1) ...
Setting up unifi (7.0.25-17292-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
[cont-init.d] 15-install: exited 0.
[cont-init.d] 19-deprecate: executing...
[cont-init.d] 19-deprecate: exited 0.
[cont-init.d] 20-config: executing...
*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
