### ISSUE TITLE
version 7.1.66-ls152 is not starting

### ISSUE THREAD

**Issue by pkhabazi** [linuxserver/docker-unifi-controller#149]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker container starts and unify management controller is running and web portal is accessible.

## Current Behavior
Latest version of docker container is starting but throwing the below error, unify management is not running and accessible:
```Shell
s6-applyuidgid: fatal: unable to exec java: No such file or directory
```

running version 7.1.66-ls151 does still start and work as expected

## Steps to Reproduce

1. run docker-compose with linuxserver/unifi-controller:latest (clean or new config)
2. running version 7.1.66-ls151 does start and work as expected
3.
4.

## Environment
**OS:** 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/20944041/172429302-707f00e2-f3b9-4e92-ba4a-502b8874b97d.png">

**CPU architecture:** armv7l (ARMv7 Processor rev 3 (v7l))
**How docker service was installed:**
 from the official docker repo,

## Command used to create docker container (run/create/compose/screenshot)

docker-compose run -d

## Docker logs

```shell
s6-applyuidgid: fatal: unable to exec java: No such file or directory
```

**Comment by j0nnymoe** [comment]
Read the whole log and also you missed this announcement https://info.linuxserver.io/issues/2022-05-31-unifi-controller/

**Comment by incomingstick** [comment]
I too am experiencing this issue. I am running aarch64 which should be supported as ARM 64-bit (per the latest release).

`uname -a`: `Linux host 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`

Here are my logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing... 
*** installing unifi packages ***
dpkg: error: cannot access archive '/app/unifi.deb': No such file or directory
[cont-init.d] 15-install: exited 2.
[cont-init.d] 19-armless: executing... 
[cont-init.d] 19-armless: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
s6-applyuidgid: fatal: unable to exec java: No such file or directory
```

Here is my docker-compose.yml:

```yml
version: '3.3'
services:
  controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi
    networks:
      - proxy
    volumes:
      - /srv/unifi:/config
    ports:
      - 8080:8080 # Unifi device inform port
      - 8443:8443 # Unifi web admin port
      - 6789:6789 # For mobile throughput test
      - 1900:1900/udp # Required for Make controller discoverable on L2 network option
      - 3478:3478/udp # Unifi STUN port
      # - 5514:5514/udp # Remote syslog port
      - 10001:10001/udp # Required for AP discovery
    restart: unless-stopped
```

Thanks!
