### ISSUE TITLE
Memory environment variables are ignored, system.properties file is never read?

### ISSUE THREAD

**Issue by aasgaard** [linuxserver/docker-unifi-controller#160]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

Version tested: 7.2.94

## Expected Behavior
The UniFi controller JVM should use the amount of memory for its heap specified in the `MEM_STARTUP`/`MEM_LIMIT` variables.

(In unifi's regular non-Docker init scripts, the UNIFI_JVM_OPTS are read from this properties file and then used as java command line arguments. This is similar to how this container worked before this commit: https://github.com/linuxserver/docker-unifi-controller/pull/119 – It is also similar to how this other container implements this variable: https://github.com/jacobalberty/unifi-docker/blob/master/docker-entrypoint.sh#L60-L62 – I suspect this earlier commit should be reverted to restore this functionality.)

## Current Behavior
The UniFi controller JVM uses Java's default amount of memory for its heap, 25% of available system/pod memory. These settings end up as lines in `system.properties`, but this file seems to be ignored.

## Steps to Reproduce

1. Set `MEM_LIMIT` (and `MEM_STARTUP` for good measure) to an arbitrary amount like `1234` and start the container.
2. Exec into a shell in the container and verify that these are there as intended by `cat`'ing `/config/data/system.properties`
3. Install JVM debugging tools we need to check the actual max heap: `apt update && apt install sudo openjdk-8-jdk-headless`
4. Run ```sudo -u abc jcmd `jcmd -l | grep -v JCmd | awk '{ print $1 }'` VM.flags``` – This should show that `MaxHeapSize` is set to 25% of the system or pod's max memory limit, in line with Java's default behavior, instead of the specified amount from the `MEM_LIMIT` environment variable (in this output shown in kilobytes).

## Environment
**OS:** Ubuntu 18.04 LTS and Google Kubernetes Engine
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repo on Ubuntu, and default managed K8s nodes on GKE

## Command used to create docker container (run/create/compose/screenshot)
Docker on Ubuntu: 

```
mkdir configtmp && docker run -d   --name=unifi-controller   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London   -e MEM_LIMIT=6666    -e MEM_STARTUP=6666   -p 8443:8443   -p 3478:3478/udp   -p 10001:10001/udp   -p 8080:8080   -v configtmp:/config   --restart unless-stopped   lscr.io/linuxserver/unifi-controller:version-7.2.94
```

On Kubernetes/GKE:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: 'unifi'
    component: controller
  name: unifi-controller
  namespace: network
spec:
  replicas: 1
  serviceName: unifi-controller
  selector:
    matchLabels:
      app: unifi
      component: controller
  template:
    metadata:
      labels:
        app: unifi
        component: controller
    spec:
      containers:
      - env:
        - name: MEM_LIMIT
          value: "10240"
        - name: MEM_STARTUP
          value: "10240"
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: 'linuxserver/unifi-controller:version-7.2.94'
        name: unifi-controller
        resources:
          limits:
            memory: 11000Mi
          requests:
            memory: 11000Mi
            cpu: 1500m
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 10001
          protocol: UDP
        - containerPort: 5514
          protocol: UDP
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8443
        - containerPort: 8843
        - containerPort: 8880
        - containerPort: 6789
        volumeMounts:
        - mountPath: /config
          name: data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      labels:
        app: unifi
        component: controller
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 40Gi
      storageClassName: premium-rwo
```

## Docker logs

```
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/15-install
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 8895 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.2.94-18697-1) ...
Setting up unifi (7.2.94-18697-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
cont-init: info: /etc/cont-init.d/15-install exited 0
cont-init: info: running /etc/cont-init.d/19-armless
cont-init: info: /etc/cont-init.d/19-armless exited 0
cont-init: info: running /etc/cont-init.d/20-config
*** Setting Java memory limit to 10240 ***
*** Setting Java memory minimum to 10240 ***
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun unifi (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```
