### ISSUE TITLE
[BUG] The new image does not start

### ISSUE THREAD

**Issue by hufhend** [linuxserver/docker-unifi-controller#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating the image to the new version 7.3.76 UniFi controller does not start

### Steps To Reproduce

cat docker-compose.yml 
```
version: "3.7"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional    
    volumes:
      - "$PWD/data:/config"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: always
```

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS, kernel 5.16.17-sun50iw9 aarch64
- How docker service was installed: Docker version 20.10.18, build b40c2f6
```

### CPU architecture

arm64

### Docker creation

```bash
lscr.io/linuxserver/unifi-controller
```

### Container logs

```
[...]
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release``
