### ISSUE TITLE
[FEAT] Split Mongo db into another container

### ISSUE THREAD

**Issue by hufhend** [linuxserver/docker-unifi-controller#196]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Separate the Mongo db into a separate container with the ability to optimize resources separately for the database and separately for the controller itself.

### Reason for change

I am running docker-unifi-controller on OrangePi Zerro 2 with 1GB RAM and finally managed to run v7.3.83. However, since v7.2.95 there has been such a slowdown that it's borderline usable. I'm not talking about boot up taking forever, even normal use is an ordeal. 
I expect this separation to make the application run faster.

### Proposed code change

```
version: "3.7"
services:
  unifi-controller:
#    image: lscr.io/linuxserver/unifi-controller:7.2.95 # last working version
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: example    
    volumes:
      - "$PWD/data:/config"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
```

**Comment by bobpaul** [comment]
Just a couple of thoughts from another user.

**Why is it like this**
First, it's self contained. There's 1 volume that contains all of the data and 1 container managing the whole service.

Second, it's running as it is because up until Unifi 5.3, that was the only way to run it. Ex: I run Unifi locally (ie, not in docker) and while I need mongo installed, but I don't start the mongo systemd service. Instead the Unifi application starts `mongod` pointed to the Unifi data directory and bound to `127.0.0.1`. In the Unifi config file I can customize the port, but I don't see a setting to point to an external mongo server. Up until Unifi 5.3, Unifi insisted on managing the mongod process.

**Migration**
I like the idea behind this change, but it will require [changing the configuration file in the image as described](https://community.ui.com/questions/External-MongoDB-Server/d311a8f8-43b6-4aeb-859d-eefec9dc1bbc#answer/b8a080b0-d05a-493c-914c-c804709c8d4a) to set point to the mongo server address and disable local control of `mongod`. (The config file is `$PWD/data/data/system.properties` in your example).

The other thing is that existing users' databases will need to be migrated to whatever folder the mongo container is using. And you'll want to make sure your Mongo container has a volume for the database files, otherwise deleting the container will drop your database (your database is currently in `$PWD/data/data/db`). 

I think it would be good if the split setup was documented (along with manual migration steps), but I'd expect most users will want to run mongod and Unifi on the same system for simplicity. But if you want to run `mongod` on a different computer, or if you want 1 `mongod` handling databases for several containers, the the split is good.

**Performance**
In the current setup, `mongod` and `unifi` are both running in the same container context on the same host. In you proposed configuration, `mongod`, `unifi`, and `mongo-express` would all be running in separate containers, but still on the same host. If this is the only thing on your Pi, this change won't increase performance.

What do resources look like on your PI? Are you running out of RAM? Memory usage would certainly go up some by adding `mongo-express` to the PI. If you have multiple containers that are each running `mongod`, then this could let you consolidate to a single `mongod` hosting several databases; that could reduce memory consumption.

Have you tried setting `MEM_LIMIT=` in your docker-compose to lower than 1024? This will reduce Unifi's ace.jar to 512MB but mongod itself will stake take ~100MB of ram.

**Comment by hufhend** [comment]
I haven't experimented with it yet. I just see that the docker image is very big. I assume this is a result of the installation coming from a regular computer installation, where Mongo is included and with that comes a certain _dependency hell_ layer. 
The standalone Mongo container is 645MB, but it is fully optimized for Mongo. The UniFi controller itself could run there in its own container with only Java. In fact, it would be nice to throw out SSL support as well, since that can be handled by another dedicated container (e.g. acme-companion).
More small containers is not a problem, but instead a benefit in terms of management, security and updates.

I can try to run Mongo externally, but then I will be running 2 Mongo's and they will both consume resources. It would make real sense with a UniFi image without Mongo.

**Comment by thespad** [comment]
So just to give you a point of reference before anyone gets too excited about super slim images, stripping out mongo takes the image from 900Mb to ~650Mb.

"throw[ing] out SSL support" isn't going to happen either, as it's a hard requirement of the controller and not something we're configuring. While it is *technically* possible to force it to listen on http, it will only do so bound to localhost, which isn't a lot of help in a container environment.

I will *look* at the options for offering a mongoless image, but it would definitely require a separate tag and if it's going to be a hassle to maintain then we're not going to do it. It's also worth considering that Unifi still do not support mongodb versions newer than 3.6, which at this point is comically old (2 years past EOL), so it's not like you're just going to be able to spin up a 6.x server and go nuts.

**Comment by hufhend** [comment]
Those super slim images would be perfect for deployment on Kubernetes as well. But I understand that SSL is wired deep in the UniFi controller itself.  
Both ingress and acme-companion can handle that.

Thank you in advance and I will look forward to it.

**Comment by bobpaul** [comment]
@thespad FWIW, Unifi does work with MongoDB < 6.0. I'm using it with v5.0.14.

**Comment by hufhend** [comment]
Thanks, I tried it and it's not going quite right. But maybe I'm the one who's wrong. I put this compose:
```
---
version: "2.1"
services:
  unifi-controller:
    image: lsiodev/unifi-controller:mongoless-7.3.83-pkg-a8cb2510-dev-748cad1a230b5b454d8fb13eae249f15abf629fa
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER= unifi
      - MONGO_PASS= secret
      - MONGO_HOST= mongo
      - MONGO_PORT= 27017
      - MONGO_DBNAME= unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - $PWD/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
  mongo:
    image: mongo:5.0.14
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: unifi
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: unifi
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://unifi:secret@mongo:27017/
    restart: always
```

and at https://localhost:8443/ it ends unfortunately with 404 and I don't see much in the log:

*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[custom-init] No custom files found, skipping...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by thespad** [comment]
The spaces, if verbatim, will definitely break things as the envs are string literals.

Otherwise you'd need to check /config/log/server.log to see where it's got to in the init, it'll be obvious if it's hung connecting to the DB.

FWIW I've only tried this with a clean install, not attempted to migrate any existing data as yet, but it works from scratch with a mongo 4.4 db at least.

**Comment by hufhend** [comment]
Those gaps were really causing problems there, after removing them and setting up the user and database (which is a bit more complicated than I would have expected) all the collections were created:
```
```

but I haven't got rid of the 404 on the main page yet.

**Comment by hufhend** [comment]
I've worked a bit on the first run, the database and user are already created automatically, but it's not quite there yet. I can see in the log:

```
[2023-03-08T23:33:41,737] <launcher> INFO  tomcat - Adding basic REST API support during the startup
[2023-03-08T23:33:44,545] <launcher> INFO  db     - waiting for db connection...
[2023-03-08T23:33:45,046] <launcher> INFO  db     - Connecting to mongodb://unifi:secret@mongo:27017/unifi
[2023-03-08T23:33:45,148] <launcher> WARN  db     - Unable to get mongodb features version: { "ok" : 0.0 , "errmsg" : "not authorized on admin to execute command { ge
tParameter: 1, featureCompatibilityVersion: 1, $readPreference: { mode: \"secondaryPreferred\" }, $db: \"admin\" }" , "code" : 13 , "codeName" : "Unauthorized"}
[2023-03-08T23:33:45,871] <launcher> WARN  db     - DbServer cannot start due to memory error, restarting with repair
```

Current docker-compose:
```
---
version: "2.1"
services:
  unifi-controller:
    image: lsiodev/unifi-controller:mongoless-7.3.83-pkg-a8cb2510-dev-748cad1a230b5b454d8fb13eae249f15abf629fa
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=secret
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - $PWD/test:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: unifi
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: unifi
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: unifi
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://unifi:secret@mongo:27017/
    restart: always
```
mongo-init.js

```db.createUser(
  {
      user: "unifi",
      pwd: "secret",
      roles: [
          {
              role: "readWrite",
              db: "unifi"
          }
      ]
  }
);
```

**Comment by hufhend** [comment]
I've worked a bit on the first run, the database and user are already created automatically, but it's not quite there yet. I can see in the log:

```
[2023-03-08T23:33:41,737] <launcher> INFO  tomcat - Adding basic REST API support during the startup
[2023-03-08T23:33:44,545] <launcher> INFO  db     - waiting for db connection...
[2023-03-08T23:33:45,046] <launcher> INFO  db     - Connecting to mongodb://unifi:secret@mongo:27017/unifi
[2023-03-08T23:33:45,148] <launcher> WARN  db     - Unable to get mongodb features version: { "ok" : 0.0 , "errmsg" : "not authorized on admin to execute command { ge
tParameter: 1, featureCompatibilityVersion: 1, $readPreference: { mode: \"secondaryPreferred\" }, $db: \"admin\" }" , "code" : 13 , "codeName" : "Unauthorized"}
[2023-03-08T23:33:45,871] <launcher> WARN  db     - DbServer cannot start due to memory error, restarting with repair
```

Current docker-compose:
```
---
version: "2.1"
services:
  unifi-controller:
    image: lsiodev/unifi-controller:mongoless-7.3.83-pkg-a8cb2510-dev-748cad1a230b5b454d8fb13eae249f15abf629fa
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=secret
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - $PWD/test:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: unifi
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: unifi
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: unifi
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://unifi:secret@mongo:27017/
    restart: always
```
mongo-init.js

```db.createUser(
  {
      user: "unifi",
      pwd: "secret",
      roles: [
          {
              role: "readWrite",
              db: "unifi"
          }
      ]
  }
);
```
