### ISSUE TITLE
Login failed on Unifi controller in docker behind reverse proxy Traefik

### ISSUE THREAD

**Issue by JBS5** [linuxserver/docker-unifi-controller#3]
I am trying to fix the login problem when accesing the Unifi Controller via Traefik at unifi.domain.nl.

Login form error:
```
Login error
There was an error making that request. Please try again later.
```
Console error:
`POST https://unifi.domain.nl/api/login 403
`

When accessing the Unifi Controller via the local IP address https://192.168.1.162:8443 I am able to login.

- I have added _insecureSkipVerify = true_ to _traefik.toml_
- 192.168.1.162 is filled in at the _Controller Hostname/IP_ setting in the Unifi Controller software.

Docker compose:
```
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${USERDIR}/docker/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
```

Traefik rule file:
```
[frontends]
  [frontends.unifi]
  backend = "unifi"
    [frontends.unifi.routes.hass]
    rule = "Host:unifi.domain.nl"
  passHostHeader = true
  passTLSCert = false
  priority = 10
  entrypoints = ["https"]
[backends]
  [backends.unifi]
    [backends.unifi.servers.server1]
    url = "https://192.168.1.162:8443"
    weight = 1

```
I do not have this kind of issues with other dockers, so I am trying the find some hints here.
Can anyone point me to a possible solution?
