### ISSUE TITLE
What platforms support arm64, if any?

### ISSUE THREAD

**Issue by paul-theorem** [linuxserver/docker-unifi-controller#39]
I am running unifi-controller on a raspberry pi 3B+.  It was running successfully in 32 bit mode for a couple weeks - but then i ran into the mongodb 32bit data size problem:

------------------------------

## Expected Behavior

unifi-controller should start in docker-compose.

## Current Behavior

pi@unifi-controller:~/unifi $ docker-compose up
Starting unifi-controller ... done
Attaching to unifi-controller
unifi-controller exited with code 159

## Steps to Reproduce
On the rpi, running raspbian, update and enable arm64

```
sudo apt-get update
sudo apt-get upgrade
```
vi /boot/config.txt:
add:
arm_64bit=1

```
sudo reboot
```
validate running arm64: 
```
pi@unifi-controller:~ $ uname -a
Linux unifi-controller 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux
```
Now, docker pull the arm64 version:
```
docker pull linuxserver/unifi-controller:arm64v8-latest
docker-compose up
```

docker-compose.yaml:

## Environment
**OS: raspbian 
```
pi@unifi-controller:~/unifi $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
**CPU architecture:** x86_64/arm32/arm64      
arm64, aarch64:
```
uname -a
Linux unifi-controller 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux

```

**How docker service was installed:**      
docker pull command above, as well as docker-compose.yaml

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller:arm64v8-latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=768M #optional
    volumes:
      - /home/pi/unifi/data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 80:8080
      - 8080:8080
      - 8081:8081
      - 443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 27117:27117
    restart: unless-stopped

```

## Docker logs
```
docker-compose up
Starting unifi-controller ... done
Attaching to unifi-controller
unifi-controller exited with code 159
```
