### ISSUE TITLE
add healthchecks to image

### ISSUE THREAD

**Issue by ToeiRei** [linuxserver/docker-unifi-controller#52]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

It's one thing to have the container 'running' - but is the service really there?
------------------------------

## Expected Behavior
A line in the dockerfile saying

`HEALTHCHECK CMD ...`

## Current Behavior

nothing in there

## Steps to Reproduce

Feel free to look at the dockerfile if you have to.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

RancherOS v1.5.6

## Command used to create docker container (run/create/compose/screenshot)

```
version: '3.6'

services:
  unifi:
    image: linuxserver/unifi-controller
    restart: unless-stopped
    ports:
     - "3478:3478/udp"
     - "10001:10001/udp"
     - "6789:6789"
     - "8080:8080"
     - "8880:8880"
     - "8443:8443"
     - "8843:8843"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`${UNIFI_HOSTNAME}`)"
      - "traefik.http.routers.unifi.entrypoints=http"

      - "traefik.http.routers.unifi-secure.rule=Host(`${UNIFI_HOSTNAME}`)"
      - "traefik.http.routers.unifi-secure.entryPoints=https"
      - "traefik.http.routers.unifi-secure.tls=true"

      - "traefik.http.services.unifi-secure.loadbalancer.server.port=8443"
      - "traefik.http.routers.unifi.middlewares=unifi-redirect"
      - "traefik.http.middlewares.unifi-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.unifi-secure.loadbalancer.server.scheme=https"
    environment:
      - TZ="Europe/Vienna"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    volumes:
      - type: volume
        source: unifi_data
        target: /config
        volume:
          nocopy: true
```
## Docker logs

none needed
