### ISSUE TITLE
Installation stuck on step 6/6, no timezones to select.

### ISSUE THREAD

**Issue by darthf1** [linuxserver/docker-unifi-controller#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I cannot get through the advanced installation, because there are no timezones available.

------------------------------

## Expected Behavior
Go through step 6 of 6 (Advanced) and finish the installation

## Current Behavior
There are no timezones to select, so the installation cannot continue

![image](https://user-images.githubusercontent.com/17253332/94948363-7dd10300-04df-11eb-8e1a-91760c22a712.png)

## Steps to Reproduce

1. Step 1 of 6 -> tick box and click next
2. Step 2 of 6 -> advanced setup -> disable both radios -> fill in local admin details -> click next
3. Step 3 of 6 (Advanced) -> click next
4. Step 4 of 6 (Advanced) -> "You have no devices" -> click next
5. Step 5 of 6 (Advanced) -> Enter WIFI credentials -> click next
6. Step 6 of 6 (Advanced) -> Select Country. Timezone select list is empty. When I click Finish, nothing happens.

## Environment
**OS:** Ubuntu 20.04.1      
**CPU architecture:** x86_64
**How docker service was installed:** Using this image in my kubernetes (microk8s) setup.

## Browser console log
![image](https://user-images.githubusercontent.com/17253332/94948561-cc7e9d00-04df-11eb-94d5-2bfe46ad9076.png)
![image](https://user-images.githubusercontent.com/17253332/94948680-fcc63b80-04df-11eb-9a89-b3bb8b50e662.png)

## Kubernetes config
`values.yaml`
```yaml
unifi:
  name: unifi
  replicaCount: 1
  image:
    repository: linuxserver/unifi-controller
    tag: latest
    pullPolicy: Always
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
  volumes:
    - name: config-volume
      hostPath:
        path: "/home/user/config/unifi"
        type: Directory
  volumeMounts:
    - name: config-volume
      mountPath: "/config"
  persistence: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
```
`unifi.deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.unifi.name }}
  labels:
    app: {{ .Values.unifi.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.unifi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.unifi.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.unifi.name }}
        release: {{ .Release.Name }}
    spec:
      volumes:
{{ toYaml .Values.unifi.volumes | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.unifi.image.repository }}:{{ .Values.unifi.image.tag }}"
          imagePullPolicy: {{ .Values.unifi.image.pullPolicy }}
          env:
{{ toYaml .Values.unifi.env | indent 12 }}
          volumeMounts:
{{ toYaml .Values.unifi.volumeMounts | indent 12 }}
          resources:
{{ toYaml .Values.unifi.resources | indent 12 }}
    {{- with .Values.unifi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.unifi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.unifi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
```
`unifi.service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.unifi.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3478
      protocol: UDP
      name: stun
    - port: 10001
      protocol: UDP
      name: ap-discovery
    - port: 8080
      name: device-communication
    - port: 8443
      name: web-admin
    - port: 1900
      protocol: UDP
      name: controller-discoverable-l2
    - port: 8843
      name: guest-portal-https
    - port: 8880
      name: guest-portal-http
    - port: 6789
      name: mobile-throughput-test
    - port: 5541
      name: remote-syslog
  selector:
    app: {{ .Values.unifi.name }}
    release: {{ .Release.Name }}
```
## Container logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /config/data/keystore -destkeystore /config/data/keystore -deststoretype pkcs12".
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
