### ISSUE TITLE
Feature request: Silence requests for data sharing after first denial

### ISSUE THREAD

**Issue by freekvh** [linuxserver/docker-unifi-controller#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I open the controller and can use it right away

## Current Behavior

Updates are more frequent than my ferequency of opening the controller website, this means I am presented with the "Do you want send us data" every time I have a quick peek at my network.

## Steps to Reproduce

1. Update dockers (in my case docker-compose pull, docker-compose up -d)
2. Open the site (like ip.addr:8443)
3. Be presented with the dialog: Please share data

## Environment
**OS:*Linux 18.04, Docker*
**CPU architecture:** x86_64
**How docker service was installed:**

Using the recommended dokcer-compose lines

## Command used to create docker container (run/create/compose/screenshot)

```
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - ./unify-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped

```

## Docker logs

No logs needed.
