### ISSUE TITLE
Initial heap size set to a larger value than the maximum heap size

### ISSUE THREAD

**Issue by DragonQ** [linuxserver/docker-unifi-controller#85]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker container should start.

## Current Behavior
Docker container fails to start and the following error is printed continuously:

```
unifi-controller    | Error occurred during initialization of VM
unifi-controller    | Initial heap size set to a larger value than the maximum heap size
```

## Steps to Reproduce

1. I am using "image: 'linuxserver/unifi-controller:latest'" in my docker compose file.
2. Ouroboros would have updated the image whenever a new version was uploaded.
3. Everything was working fine about a week ago, now this problem is occuring with no other changes, so this must have broken in a recent version.
4. I've tried increasing MEM_LIMIT to no avail.
5. Removing MEM_LIMIT entirely seems to fix the issue. Has the behaviour of this environment variable changed?

## Environment
**OS:** Ubuntu 20.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:** Distro repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: '3.7'
services:
    unifi-controller:
        container_name: unifi-controller
        image: 'linuxserver/unifi-controller:latest'
        restart: unless-stopped
        volumes:
            - ${ROOT_PATH}/config:/config
        ports:
            - '${UNIFI_STUN_PORT}:3478/udp'
            - '${AP_DISCOVOERY_PORT}:10001/udp'
            - '${DEVICE_COMMS_PORT}:8080'
            - '${WEB_GUI_PORT}:8443'
        environment:
            - MEM_LIMIT=${MEM_LIMIT}
```
env:
```
# Root path
ROOT_PATH=/home/docker/unifi-controller

# Ports
UNIFI_STUN_PORT=3478
AP_DISCOVOERY_PORT=10001
DEVICE_COMMS_PORT=8080
WEB_GUI_PORT=8443

# Environment
MEM_LIMIT=512M

```
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
...
```
