### ISSUE TITLE
Devices on local network change inform URL to container internal IP and revert to adopting state 

### ISSUE THREAD

**Issue by workalt23184** [linuxserver/docker-unifi-controller#87]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Devices should use the hostname set in the controller under `Controller Hostname/IP` for inform URL, or the one set manually with `set-inform` if the override inform option is disabled. 

## Current Behavior

Devices on the local network (same subnet as the host that is running Docker) have their inform URL changed to point at the container's IP on the internal docker network (e.g `http://172.18.0.6:8080/inform`) which is not routable. I have set the controller hostname setting to the full DNS hostname of the controller and tried disabling the override inform and make controller discoverable settings with no luck. SSHing in to the device and running `set-inform http://unifi.[REDACTED].com:8080/inform` allows it to connect to the controller again for about a day, then the inform URL reverts to the incorrect one. This does not happen to our ~50 other sites on this controller.

## Steps to Reproduce

1. Start unifi container (`docker-compose.yml` bellow).
2. Restore backup on container.
3. All devices online.
4. Wait ~1 day.
5. Device status is cycling between Adopting and Disconnected every few seconds.
6. SSH into device, running `info` command returns `Status: Timeout (http://172.18.0.6:8080/inform)`.
7. Run `set-inform http://unifi.[REDACTED].com:8080/inform`, device comes online.
8. Repeat 4-7, but disable  override inform and make controller discoverable settings, same result.

## Environment
**OS:** Ubuntu 20.04.2 LTS
**CPU architecture:** x86_64
**How docker service was installed:** From `https://download.docker.com/linux/ubuntu` repo.

The web ui is being peroxided by Traefik to provide HTTPS, but the other ports are exposed directly.

## Command used to create docker container (run/create/compose/screenshot)

``` yml
version: "3.8"

services:
  server:
    image: ghcr.io/linuxserver/unifi-controller:version-6.2.26
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=4096M #optional
      - MEM_STARTUP=2048M #optional

    volumes:
      - config:/config
    networks:
      - traefik2_proxy # Reqired on the container that will be exposed by traefik.
      - default # Include the default per-compose-project network. Unneeded if you don't specify the `networks` key.
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      #- 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    labels:
      - "traefik.enable=true" # Only on the container that will be exposed
      - "traefik.http.routers.unifi.rule=Host(`unifi.[REDACTED].com`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443" #If the internal port is not auto detected, set it here.
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"

volumes:
    config:

networks:
  traefik2_proxy:
    external: true
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
:0 Permanent error code on channel bind request: 403 - Forbidden IP
:0 All TURN channel bindings failed
:0 STUN id:   7; fd: 255 172.18.0.6:49788 -> 68.202.254.208:55115 (eth0) DTLS id: 16 (96.[x.x.x REDACTED]:49788) (PEER) timed out
:0 webRtcId 1 terminated with code: (-2147090409) WebRTC connection interrupted from far side
```

Based on the IP on the STUN line, that error at the bottom is from the connection from my PC to the web GUI, we have no UniFi devices with that public IP.
